controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

pokemon_type_training:
    path: '/pokemons/{id}/training'
    controller: 'App\Controller\PokemonTypeController::training'
    methods: [POST]
