#index:
#    path: /
#    controller: App\Controller\DefaultController::index

buy_pokemon:
    path: /buy/{id}
    controller: App\Controller\CommerceController::buyPokemon
    methods: [GET, POST]
pokemon_type_sell:
  path: /sell/{id}
  controller: App\Controller\CommerceController::sellPokemon
  methods: [GET, POST]

confirm_purchase:
  path: /buy/{id}
  controller: App\Controller\CommerceController::confirmPurchase
  methods: [GET, POST]
